### ISSUE TITLE
Install files should be deleted after install

### ISSUE THREAD

**Issue by dansteele** [clupprich/ruby-build-action#2]
Otherwise tools like Rubocop see the files.

Assuming something along the lines of

```js
    core.info(`Removing ruby-build install files`)
    await exec.exec(`rm -rf ./ruby-build`)
```

would do the trick.

**Comment by clupprich** [comment]
Ah, that's a great find! Maybe we should install `ruby-build` somewhere else, like `HOME`, not into the project that's beeing checked out?

**Comment by dansteele** [comment]
:shipit:
